### ISSUE TITLE
Der gleiche Ton über beide Szenen

### ISSUE THREAD

**Issue by csteins1** [VeraCologne/aframe#49]
Der Ton soll auch weiterlaufen, wenn man die Szene im Laden verlässt. Wenn man danach den Laden wieder betritt läuft die Szene "weiter". Man hört also den ganzen Ton, verpasst aber visuell den Teil, während man nicht im Laden ist.

**Comment by SoerenTerh** [comment]
Notiz für mich: momentanen Stand in localStorage/sessionStorage

**Comment by SoerenTerh** [comment]
Zu speichern, an welchem Punkt die Story steht, ist kein Problem. Da wir aber die Figuren prozedual bewegen und nicht nachverfolgen, wo sie an welchem Storyabschnitt stehen sollen, ist das leider mit momentanem Stand der Storyabfolge nicht möglich.
