### ISSUE TITLE
Beschriftung der Läden

### ISSUE THREAD

**Issue by csteins1** [VeraCologne/aframe#50]

**Comment by csteins1** [comment]
dadurch, dass alles totalmerkwürdig bennant wurde, habe ich die baecker.max zur baeckerei.dae, den teppichladen.max zum teppichladen.dae und den tabakladen.max zum tabakladen1.dae umgewandelt.

**Comment by mbruess1** [comment]
max zu dae? 😧 wollten wir nicht beides haben? 🙈

**Comment by csteins1** [comment]
es ist beides drin.
