### ISSUE TITLE
Webseite aktualisieren

### ISSUE THREAD

**Issue by csteins1** [VeraCologne/aframe#57]
& Zusammenfassen, was wir gemacht habe, aber nicht umsetzbar war
& PPT
& final sparkle

**Comment by csteins1** [comment]
weiter ausführen?

**Comment by mbruess1** [comment]
Ich bin soweit fertig. Es fehlt noch eine Datei, die mir @csteins1 aber noch schicken will. Vielleicht könnt ihr ja mal drüber schauen wenn ihr eure Seiten nicht mehr sehen könnt ;)
